services:
  frontend:
    build:
      context: ./app
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend
      - ./app/shared:/app/shared
      - ./app/config:/app/config
      - /app/frontend/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    command: yarn workspace @staymatic/frontend dev

  backend:
    build:
      context: ./app
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./app/backend:/app/backend
      - ./app/shared:/app/shared
      - ./app/config:/app/config
      - /app/backend/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
    command: yarn workspace @staymatic/backend dev 