services:
  frontend:
    build:
      context: ./app
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./app
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production 