services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: staymatic

  frontend:
    build:
      context: .
      dockerfile: app/docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend
      - ./app/shared:/app/shared
      - ./app/config:/app/config
      - /app/frontend/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    command: yarn workspace @staymatic/frontend dev

  backend:
    build:
      context: .
      dockerfile: app/docker/backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./app/backend:/app/backend
      - ./app/shared:/app/shared
      - ./app/config:/app/config
      - /app/backend/node_modules
      - /app/shared/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/staymatic?authSource=admin
      - BETTER_AUTH_SECRET=your-super-secret-key-for-development-minimum-32-characters
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:3001
    depends_on:
      - mongodb
    command: yarn workspace @staymatic/backend dev

volumes:
  mongodb_data: